/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.capgi.ipl;

public class IplLeagueAnalyser {
	public static void main(String[] args) {
		System.out.println("Welcome to Ipl league analyser");
	}
}
