/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.capgi.ipl;

import org.junit.Test;

public class IplLeagueAnalyserTest {
	@Test
	public void testSomeLibraryMethod() {

	}
}
